name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: brew install hadolint
      - run: |
          hadolint jdk{8,11}/*Dockerfile
          hadolint jre8/*Dockerfile
