name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: brew install hadolint
      - run: |
          hadolint jdk/{8,11,17,21}/*Dockerfile
          hadolint maven/eclipse-temurin-{8,11,17,21}/*Dockerfile
          hadolint maven-mvnd/eclipse-temurin-{8,11,17,21}/*Dockerfile
          hadolint jre8/*Dockerfile
          hadolint code/*Dockerfile
          hadolint ubuntu-playground/*Dockerfile
