name: Build JDK Docker

on:
  pull_request:
  push:
    paths:
      - jdk/**
      - .github/workflows/jdk.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-file:
          - path: jdk/8
            image: shenlw/jdk,registry.cn-shanghai.aliyuncs.com/lwshen/jdk
            tags: 8,8-eclipse-temurin
            platforms: linux/amd64,linux/arm64,linux/arm/v7

          - path: jdk/11
            image: shenlw/jdk,registry.cn-shanghai.aliyuncs.com/lwshen/jdk
            tags: 11,11-eclipse-temurin
            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/s390x

          - path: jdk/17
            image: shenlw/jdk,registry.cn-shanghai.aliyuncs.com/lwshen/jdk
            tags: 17,17-eclipse-temurin
            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/s390x

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGES=$(echo ${{ matrix.docker-file.image }} | tr "," "\n")
          DOCKER_IMAGE=${DOCKER_IMAGES[0]}

          TAGZ=$(echo ${{ matrix.docker-file.tags }} | tr "," "\n")
          VERSION=${TAGZ[0]}

          for image in $DOCKER_IMAGES
          do
            for tag in $TAGZ
            do
              TAGS="${TAGS},${image}:${tag}"
            done
          done

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}

          find ./maven -maxdepth 1 -type d -exec cp -r ./maven/settings-docker.xml {} \;

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Buildx (build)
        uses: docker/build-push-action@v2.7.0
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: ${{ matrix.docker-file.platforms }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Docker Login
        if: success() && contains(github.ref, 'master')
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          region-id: cn-shanghai
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Docker Buildx (push)
        uses: docker/build-push-action@v2.7.0
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          platforms: ${{ matrix.docker-file.platforms }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Docker Check Manifest
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'master')
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}

      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json