name: Build Maven Docker

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - maven/**
      - .github/workflows/maven.yml
      - constants.env

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-file:
          - path: maven/eclipse-temurin-8
            image: shenlw/maven
            tag_suffixes: jdk-8, eclipse-temurin-8
            platforms: linux/amd64,linux/arm64,linux/arm/v7

          - path: maven/eclipse-temurin-11
            image: shenlw/maven
            tag_suffixes: jdk-11, eclipse-temurin-11
            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/s390x

          - path: maven/eclipse-temurin-17
            image: shenlw/maven
            tag_suffixes: jdk-17, eclipse-temurin-17
            platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/s390x

          - path: maven/eclipse-temurin-21
            image: shenlw/maven
            tag_suffixes: jdk-21, eclipse-temurin-21
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: "constants.env"
          expand: "true"

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{ matrix.docker-file.image }}

          TAG_SUFFIXES=$(echo ${{ matrix.docker-file.tag_suffixes }} | tr "," "\n")
          VERSION=${{ env.MAVEN_VERSION }}
          major=`echo $VERSION | cut -d. -f1`
          minor=`echo $VERSION | cut -d. -f2`
          revision=`echo $VERSION | cut -d. -f3`

          for tag in $TAG_SUFFIXES
          do
            TAGS="${TAGS},${DOCKER_IMAGE}:${major}-${tag}"
            TAGS="${TAGS},${DOCKER_IMAGE}:${major}.${minor}-${tag}"
            TAGS="${TAGS},${DOCKER_IMAGE}:${major}.${minor}.${revision}-${tag}"
          done

          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

          find ./maven -maxdepth 1 -type d -exec cp -r ./maven/settings-docker.xml {} \;
          find ./maven -maxdepth 1 -type d -exec cp -r ./maven/mvn-entrypoint.sh {} \;

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Buildx (build)
        uses: docker/build-push-action@v3
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: |
            REFRESHED_AT=$(date +%Y-%m-%d)
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}
          platforms: ${{ matrix.docker-file.platforms }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Docker Login
        if: success() && contains(github.ref, 'master')
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        uses: docker/build-push-action@v3
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: |
            REFRESHED_AT=$(date +%Y-%m-%d)
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}
          platforms: ${{ matrix.docker-file.platforms }}
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Docker Check Manifest
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'master')
        run: |
          for tag in $(echo ${{ steps.prepare.outputs.tags }} | tr "," "\n")
          do
            docker run --rm mplatform/mquery ${tag}
          done

      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json
