name: Build Maven Docker (ACR)

on:
  pull_request:
  push:
    paths:
      - maven/**
      - .github/workflows/maven-acr.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-file:
          - path: maven/eclipse-temurin-8
            image: registry.cn-shanghai.aliyuncs.com/lwshen/maven
            tags: 3.8.6-jdk-8, 3.8-jdk-8, 3-jdk-8, 3.8.6-eclipse-temurin-8, 3.8-eclipse-temurin-8, 3-eclipse-temurin-8

          - path: maven/eclipse-temurin-11
            image: registry.cn-shanghai.aliyuncs.com/lwshen/maven
            tags: 3.8.6-jdk-11, 3.8-jdk-11, 3-jdk-11, 3.8.6-eclipse-temurin-11, 3.8-eclipse-temurin-11, 3-eclipse-temurin-11

          - path: maven/eclipse-temurin-17
            image: registry.cn-shanghai.aliyuncs.com/lwshen/maven
            tags: 3.8.6-jdk-17, 3.8-jdk-17, 3-jdk-17, 3.8.6-eclipse-temurin-17, 3.8-eclipse-temurin-17, 3-eclipse-temurin-17

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{ matrix.docker-file.image }}

          TAGZ=$(echo ${{ matrix.docker-file.tags }} | tr "," "\n")
          VERSION=${TAGZ[0]}

          for tag in $TAGZ
          do
            TAGS="${TAGS},${DOCKER_IMAGE}:${tag}"
          done

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}

          find ./maven -maxdepth 1 -type d -exec cp -r ./maven/settings-docker.xml {} \;
          find ./maven -maxdepth 1 -type d -exec cp -r ./maven/mvn-entrypoint.sh {} \;

      - name: Docker Buildx (build)
        uses: docker/build-push-action@v2.7.0
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        if: success() && contains(github.ref, 'master')
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Docker Buildx (push)
        uses: docker/build-push-action@v2.7.0
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Docker Check Manifest
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'master')
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}

      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json