name: Build mvnd Docker (ACR)

on:
  pull_request:
  push:
    paths:
      - maven-mvnd/**
      - .github/workflows/mvnd-acr.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker-file:
          - path: maven-mvnd/eclipse-temurin-8
            image: registry.cn-shanghai.aliyuncs.com/lwshen/mvnd
            tags: 0.7.1-jdk-8, 0.7-jdk-8, 0.7.1-eclipse-temurin-8, 0.7-eclipse-temurin-8

          - path: maven-mvnd/eclipse-temurin-11
            image: registry.cn-shanghai.aliyuncs.com/lwshen/mvnd
            tags: 0.7.1-jdk-11, 0.7-jdk-11, 0.7.1-eclipse-temurin-11, 0.7-eclipse-temurin-11

          - path: maven-mvnd/eclipse-temurin-17
            image: registry.cn-shanghai.aliyuncs.com/lwshen/mvnd
            tags: 0.7.1-jdk-17, 0.7-jdk-17, 0.7.1-eclipse-temurin-17, 0.7-eclipse-temurin-17

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=${{ matrix.docker-file.image }}

          TAGZ=$(echo ${{ matrix.docker-file.tags }} | tr "," "\n")
          VERSION=${TAGZ[0]}

          for tag in $TAGZ
          do
            TAGS="${TAGS},${DOCKER_IMAGE}:${tag}"
          done

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}

          find ./maven-mvnd -maxdepth 1 -type d -exec cp -r ./maven/settings-docker.xml {} \;

      - name: Docker Buildx (build)
        uses: docker/build-push-action@v2.7.0
        if: success() && !contains(github.ref, 'master')
        with:
          push: false
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        if: success() && contains(github.ref, 'master')
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Docker Buildx (push)
        uses: docker/build-push-action@v2.7.0
        if: success() && contains(github.ref, 'master')
        with:
          push: true
          context: ./${{ matrix.docker-file.path }}
          file: ./${{ matrix.docker-file.path }}/Dockerfile
          build-args: REFRESHED_AT=$(date +%Y-%m-%d)
          tags: ${{ steps.prepare.outputs.tags }}

      - name: Docker Check Manifest
        if: always() && github.event_name != 'pull_request' && contains(github.ref, 'master')
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}

      - name: Clear
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json